[package]
name = "mod-util"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description.workspace = true
authors.workspace = true
publish.workspace = true



[dependencies]
# bit 수준 Flag를 생성하는 라이브러리
# License: MIT or Apache-2.0
bitflags = "2.6"

# 데이터 직렬화 라이브러리
# License: MIT or Apache-2.0
serde = { version = "1.0", features = ["derive"] }

# 윈도우 생성 라이브러리
# License: Apache-2.0
winit = { version = "0.30", features = ["rwh_05"] }

# 크로스 플랫폼 렌더링 라이브러리 
# License: MIT or Apache-2.0
wgpu = "22"
