[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.86"
description = "2024년 한국공학대학교 게임공학과 졸업작품"
authors = [
    "HK416 <powerspirit127@gmail.com>", 
    "Jirung-E <jh10590326@gmail.com>", 
    "HA0_TUK <hayoungtuk@gmail.com>"
]
publish = false



[workspace.dependencies]
# A non-cryptographic hash function using AES-NI for high performance
# License: MIT OR Apache-2.0
ahash = "0.8"

# A macro to generate structures which behave like bitflags.
# License: MIT OR Apache-2.0
bitflags = "2.9"

# A crate for mucking around with piles of bytes.
# License: Zlib OR Apache-2.0 OR MIT
bytemuck = { version = "1.20", features = ["derive"] }

# Date and time library for Rust
# License: MIT OR Apache-2.0
chrono = "0.4"

# concat! with support for const variables and expressions
# License: MIT OR Apache-2.0
constcat = "0.6"

# Blazing fast concurrent HashMap for Rust.
# License: MIT
dashmap = "6.1"

# An easy-to-use immediate mode GUI that runs on both web and native
# License: MIT OR Apache-2.0
egui = "0.31"

# Bindings for using egui with winit
# License: MIT OR Apache-2.0
egui-winit = "0.31"

# A simple and fast 3D math library for games and graphics
# License: MIT OR Apache-2.0
glam = { version = "0.30", features = ["bytemuck", "rand"] }

# Half-precision floating point f16 and bf16 types for Rust implementing the IEEE 754-2008 standard binary16 and bfloat16 types.
# License: MIT OR Apache-2.0
half = "2.6"

# A fast, minimal, and ergonomic entity-component-system library
# License: MIT OR Apache-2.0
hecs = "0.10"

# A macro for declaring lazily evaluated statics in Rust.
# License: MIT OR Apache-2.0
lazy_static = "1.5"

# A lightweight logging facade for Rust
# License MIT OR Apache-2.0
log = "0.4"

# Get the number of CPUs on a machine.
# License: MIT OR Apache-2.0
num_cpus = "1.16"

# More compact and efficient implementations of the standard synchronization primitives.
# License: MIT OR Apache-2.0
parking_lot = { version = "0.12", features = ["hardware-lock-elision"] }

# Random number generators and other randomness functionality.
# License: MIT OR Apache-2.0
rand = "0.9"

# Simple work-stealing parallelism for Rust
# License: MIT OR Apache-2.0
rayon = "1.10"

# Application-level tracing for Rust.
# License: MIT
tracing = "0.1"

# Utilities for implementing and composing `tracing` subscribers.
# License: MIT
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Provides utilities for file appenders and making non-blocking writers.
# License: MIT
tracing-appender = "0.2"

# A generic serialization/deserialization framework
# License: MIT or Apache-2.0
serde = { version = "1.0", features = ["derive"] }

# A JSON serialization file format
# License: MIT OR Apache-2.0
serde_json = "1.0"

# Spin-based synchronization primitives
# License: MIT
spin = "0.10"

# Compile-time assertions to ensure that invariants are met.
# License: MIT OR Apache-2.0
static_assertions = "1.1"

# derive(Error)
# License: MIT OR Apache-2.0
thiserror = "2.0"

# Rusty WebGPU API wrapper
# License: MIT OR Apache-2.0
wgpu = "26"

# Cross-platform window creation library.
# License: Apache-2.0
winit = { version = "0.30", features = ["serde"] }
