[package]
name = "mod-asset"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description.workspace = true
authors.workspace = true
publish.workspace = true



[dependencies]
# Math library for video games
# License: MIT
gmm = { git = "https://github.com/HK416/gmm.git", features = ["bytemuck", "serde"] }

# A generic serialization/deserialization framework
# License: MIT or Apache-2.0
serde = { version = "1.0", features = ["derive"] }

# Rusty WebGPU API wrapper
# License: MIT or Apache-2.0
wgpu = { version = "22", features = ["serde"] }



# 자체 프레임워크 라이브러리
mod-physics = { path = "../mod-physics" }
mod-world = { path = "../mod-world" }
