[package]
name = "mod-error"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description.workspace = true
authors.workspace = true
publish.workspace = true



[dependencies]
# 로그 인터페이스 라이브러리
# License: MIT or Apache-2.0
log = "0.4"

# 에러 타입을 쉽게 만들어주는 라이브러리
# License: MIT or Apache-2.0
thiserror = "1.0"

# 윈도우 생성 라이브러리
# License: Apache-2.0
winit = { version = "0.30", features = ["rwh_05"] }



# 자체 프레임워크 라이브러리
mod-parallelism = { path = "../mod-parallelism" }



[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
# 사용 플랫폼: Windows, macOS
# 시스템 대화 상자를 화면에 표시하는 라이브러리
# License: MIT or Apache-2.0
native-dialog = "0.7"



[features]
default = ["enable-debug-info"]

enable-debug-info = []
