[package]
name = "mod-app"
version = "0.4.0"
edition.workspace = true
rust-version.workspace = true
description.workspace = true
authors.workspace = true
publish.workspace = true



[dependencies]
# A macro to generate structures which behave like bitflags.
# License: MIT OR Apache-2.0
bitflags = "2.6"

# A fast, minimal, and ergonomic entity-component-system library
# License: MIT OR Apache-2.0
hecs = "0.10"

# A macro for declaring lazily evaluated statics in Rust.
# License: MIT OR Apache-2.0
lazy_static = "1.5"

# A lightweight logging facade for Rust
# License: MIT OR Apache-2.0
log = "0.4"

# Rusty File Dialog
# License: MIT
rfd = "0.15"

# A generic serialization/deserialization framework
# License: MIT OR Apache-2.0
serde = "1.0"

# derive(Error)
# License: MIT OR Apache-2.0
thiserror = "1.0"

# Cross-platform window creation library.
# License: Apache-2.0
winit = "0.30"

# Rusty WebGPU API wrapper
# License: MIT OR Apache-2.0
wgpu = "22"



# 자체 프레임워크 라이브러리
mod-network = { path = "../mod-network" }
mod-parallelism = { path = "../mod-parallelism" }
mod-world = { path = "../mod-world" }



# 사용 플랫폼: Windows
[target.'cfg(target_os = "windows")'.dependencies]
# Rust for Windows
# License: MIT OR Apache-2.0
windows = { version = "0.58", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }



# 사용 플랫폼: Windows, macOS
[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
# Synchronously block the thread until a future completes
# License: Apache-2.0 OR MIT
pollster = "0.3"





[features]
default = ["command-line-args"]

# 명령줄 인수를 허용합니다.
command-line-args = []
