[package]
name = "mod-app"
version = "0.7.0"
edition.workspace = true
rust-version.workspace = true
description.workspace = true
authors.workspace = true
publish.workspace = true



[dependencies]
ahash = { workspace = true }
bitflags = { workspace = true }
bytemuck = { workspace = true }
dashmap = { workspace = true }
egui = { workspace = true }
egui-winit = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
parking_lot = { workspace = true }
rayon = { workspace = true }
rodio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }

# Rusty File Dialog
# License: MIT
rfd = "0.15"

# Utilities for handling networking sockets with a maximal amount of configuration possible intended.
# License: MIT OR Apache-2.0
socket2 = { version = "0.6", features = ["all"]}

# 자체 프레임워크 라이브러리
mod-network = { path = "../mod-network" }
mod-parallelism = { path = "../mod-parallelism"}
mod-render = { path = "../mod-render" }



# 사용 플랫폼: Windows
[target.'cfg(target_os = "windows")'.dependencies]
# Rust for Windows
# License: MIT OR Apache-2.0
windows = { version = "0.61", features = [
    "Win32_Foundation", 
    "Win32_UI_WindowsAndMessaging", 
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Graphics_Gdi"
] }



# 사용 플랫폼: Windows, macOS
[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
# Synchronously block the thread until a future completes
# License: Apache-2.0 OR MIT
pollster = "0.4"



[features]
default = ["dev"]

# 개발자 옵션
dev = ["command-line-args", "enable-shader-validation"]

# 명령줄 인수를 허용합니다.
command-line-args = []
# 쉐이더 생성시 유효성 검사를 활성화합니다.
enable-shader-validation = []
