[package]
name = "mod-render"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description.workspace = true
authors.workspace = true
publish.workspace = true


[dependencies]
ahash = { workspace = true }
bitflags = { workspace = true }
bytemuck = { workspace = true }
dashmap = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }

# Compile-time assertions to ensure that invariants are met.
# License: MIT OR Apache-2.0
static_assertions = "1.1"



[features]
# 쉐이더 디버깅 레이어를 활성화합니다.
enable-debug-layer = []

# 쉐이더 생성시 유효성 검사를 활성화합니다.
enable-shader-validation = []
