[package]
name = "mod-render"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
description.workspace = true
authors.workspace = true
publish.workspace = true



[dependencies]
# A crate for mucking around with piles of bytes.
# License: Zlib OR Apache-2.0 OR MIT
bytemuck = { version = "1.18", features = ["derive"] }

# Math library for video games
# License: MIT
gmm = { version = "0.2", features = ["bytemuck"] }

# A macro for declaring lazily evaluated statics in Rust.
# License: MIT OR Apache-2.0
lazy_static = "1.5"

# A lightweight logging facade for Rust
# License: MIT OR Apache-2.0
log = "0.4"

# Compile-time assertions to ensure that invariants are met.
# License: MIT OR Apache-2.0
static_assertions = "1.1"

# derive(Error)
# License: MIT OR Apache-2.0
thiserror = "1.0"

# Cross-platform window creation library.
# License: Apache-2.0
winit = "0.30"

# 크로스 플랫폼 렌더링 라이브러리 
# License: MIT or Apache-2.0
wgpu = "22"



[features]
default = ["enable-shader-validation"]

# 쉐이더 유효성 검증을 활성화 합니다.
enable-shader-validation = []
