[package]
name = "mod-network"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
description.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
# Math library for video games
# License: MIT
gmm = { git = "https://github.com/HK416/gmm.git", features = ["bytemuck", "serde"] }

local-ip-address = "0.6.2"

mod-math = { path = "../mod-math" }
serde = { workspace = true }