[package]
name = "mod-network"
version = "0.5.0"
edition.workspace = true
rust-version.workspace = true
description.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
bitflags = { workspace = true }
glam = { workspace = true }
half = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wgpu = { workspace = true }

local-ip-address = "0.6.2"

[features]
default = ["check-validation"]

# 유효성 검사를 활성화합니다.
check-validation = []
