[package]
name = "framework"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
description.workspace = true
authors.workspace = true
publish.workspace = true



[dependencies]
# 물리적 코어의 갯수를 가져오는 라이브러리
# License: MIT or Apache-2.0
num_cpus = "1.16"

# Lazy initialization 라이브러리
# License: MIT or Apache-2.0
lazy_static = "1.5"
